export const RECEIVE_ROOM = 'RECEIVE_ROOM';
export const REQUEST_ROOM = 'REQUEST_ROOM';

export const RECEIVE_ROOM_EVENTS = 'RECEIVE_ROOM_EVENTS';
export const REQUEST_ROOM_EVENTS = 'REQUEST_ROOM_EVENTS';
