export const RECEIVE_ROOM = 'RECEIVE_ROOM';
export const REQUEST_ROOM = 'REQUEST_ROOM';

export const RECEIVE_ROOMS = 'RECEIVE_ROOMS';
export const REQUEST_ROOMS = 'REQUEST_ROOMS';

export const RECEIVE_EVENTS = 'RECEIVE_EVENTS';
export const RECEIVE_EVENT_HISTORY = 'RECEIVE_EVENT_HISTORY';

export const REQUEST_AUTHENTICATION = 'REQUEST_AUTHENTICATION';
export const RECEIVE_AUTHENTICATION = 'RECEIVE_AUTHENTICATION';
export const RECEIVE_LOGOUT = 'RECEIVE_LOGOUT';
