export const Actions = {
  REQUEST_ROOM: 'REQUEST_ROOM',
  RECEIVE_ROOM: 'RECEIVE_ROOM',
  REQUEST_ROOMS: 'REQUEST_ROOMS',
  RECEIVE_ROOMS: 'RECEIVE_ROOMS',
  ROOM_CREATED: 'ROOM_CREATED',

  RECEIVE_EVENTS: 'RECEIVE_EVENTS',
  RECEIVE_EVENT_HISTORY: 'RECEIVE_EVENT_HISTORY',

  REQUEST_AUTHENTICATION: 'REQUEST_AUTHENTICATION',
  RECEIVE_AUTHENTICATION: 'RECEIVE_AUTHENTICATION',
  RECEIVE_LOGOUT: 'RECEIVE_LOGOUT'
};
